spring.application.name=labor-settlement-calculator

# URLs
bacen.api.sgs.selic.url=https://api.bcb.gov.br/dados/serie/bcdata.sgs.4390/dados?formato=json
bacen.api.sgs.selic.url.filter=&dataInicial=%s&dataFinal=%s
